# Generated by Django 6.0.1 on 2026-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
