"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment when available; falls back to a dev-only key.
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-rn3&sbo%u7xohsa7mj%cc$19_(^s68tol5yq5q3lc9ti(w!05m'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment-driven DEBUG to allow safe production configs.
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# Allowed hosts can be provided via environment; defaults for local dev.
# Trim spaces to avoid invalid host entries from env values.
ALLOWED_HOSTS = [h.strip() for h in os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost'
).split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'jobAccess',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve static files efficiently in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Allow overriding the database via DATABASE_URL (e.g., Vercel Postgres)
_db_url = os.getenv('DATABASE_URL')
if _db_url:
    DATABASES['default'] = dj_database_url.parse(_db_url, conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# --- Deployment environment detection ---
# Detect deployment platform before configuring static files
IS_VERCEL = os.getenv('VERCEL') == '1' or os.getenv('VERCEL_ENV') is not None
IS_RENDER = os.getenv('RENDER') is not None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# On Vercel, serve static files directly from repo via routing
STATIC_URL = '/static/'

# Where collectstatic will place files for production serving
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Keep app-level static in development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Enable compressed manifest storage for stable cache busting in prod
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL configuration
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# --- Security settings for production (safe defaults) ---
if not DEBUG:
    # Force HTTPS and set HSTS
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional recommended headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # CSRF trusted origins (optional, comma-separated)
    _trusted = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
    if _trusted:
        CSRF_TRUSTED_ORIGINS = [x.strip() for x in _trusted.split(',') if x.strip()]

# --- Vercel runtime adjustments ---
# Vercel serves static assets directly from the repository, so avoid WhiteNoise
# and manifest storage that requires collectstatic on ephemeral builds.

if IS_VERCEL:
    # Remove WhiteNoise middleware if present
    MIDDLEWARE = [m for m in MIDDLEWARE if not m.startswith('whitenoise.')]
    # Use default static files storage; rely on Vercel to serve /static/*
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    # Allow Vercel dynamic preview and project domains by default
    if '.vercel.app' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.vercel.app')

if IS_RENDER:
    # Allow Render domains
    if '.onrender.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.onrender.com')

# PythonAnywhere configuration
IS_PYTHONANYWHERE = 'PYTHONANYWHERE_DOMAIN' in os.environ or 'pythonanywhere.com' in os.getenv('HTTP_HOST', '')
if IS_PYTHONANYWHERE:
    # Allow PythonAnywhere domains
    if '.pythonanywhere.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.pythonanywhere.com')
